//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8830
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW.Localisation.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class id_ID {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal id_ID() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSW.Localisation.Messages.id-ID", typeof(id_ID).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukses.
        /// </summary>
        public static string HT_COM_CAP001 {
            get {
                return ResourceManager.GetString("HT_COM_CAP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galat.
        /// </summary>
        public static string HT_COM_CAP002 {
            get {
                return ResourceManager.GetString("HT_COM_CAP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringatan.
        /// </summary>
        public static string HT_COM_CAP003 {
            get {
                return ResourceManager.GetString("HT_COM_CAP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmasi.
        /// </summary>
        public static string HT_COM_CAP004 {
            get {
                return ResourceManager.GetString("HT_COM_CAP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_COM_MS008: Jaringan tidak tersedia..
        /// </summary>
        public static string HT_COM_MS008 {
            get {
                return ResourceManager.GetString("HT_COM_MS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_COM_MS029: Aplikasi yang sama sedang berjalan.
        /// </summary>
        public static string HT_COM_MS029 {
            get {
                return ResourceManager.GetString("HT_COM_MS029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_COM_MS040: Sepertinya server terlalu lama merespons, silakan coba lagi nanti.
        /// </summary>
        public static string HT_COM_MS040 {
            get {
                return ResourceManager.GetString("HT_COM_MS040", resourceCulture);
            }
        }
    }
}
